### ISSUE TITLE
Request: Demo

### ISSUE THREAD

**Issue by Braunson** [SolBegAgent/SolbegLaravelVueValidation#7]
In the docs you mention including the asset script after Vue + VeeValidate, which I do but then it mentions adding in the `Vue::use` line in Vue which won't work since your including this asset script after Vue/VeeValidate.

This results in `SolbegLaravelVueValidation is not defined`

**Comment by Stereotip42** [comment]
You can require this package by adding a script at the end of your main layout like this:
```
<head>...</head>
<body>
  <div id="app"></div>
  <script type="text/javascript" src="{{mix('/js/app.js')}}"></script>
  <script type="text/javascript" src="{{mix('/js/vue.js')}}"></script>
  <script>
    Vue.use(VeeValidate);
    Vue.use(SolbegLaravelVueValidation);
  </script>
</body>
```
